[platformio]
default_envs = esp32-espidf

[env:esp32-espidf]
platform = espressif32
board = esp32cam
framework = espidf
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder
build_flags = 
    -I include
    -Wall
    -Wextra
upload_speed = 115200

[env:esp32-arduino]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder
build_flags = 
    -I include
    -Wall
